### ISSUE TITLE
Las gestiones no deberían tener sus métodos estáticos 

### ISSUE THREAD

**Issue by lucianogaregnani** [Gann4Life/TP2FINAL#6]
El problema que noto dentro de la clase GestionTurno, es que el singleton que se implementa dentro de está no tienen ninguna utilidad, ya que en ningún momento va a necesitar ser instanciada.
Con solamente poner un **GestionTurnos.registrarTurno()**, al ser estático, no necesita de una instancia para poder acceder al mismo.
Para esto se me ocurrieron dos soluciones: 
- Que no haya ningún método y atributo estático, y que cada clase que utilice GestionTurnos tenga un atributo de la misma, lógicamente manteniendo el singleton.
- Que todos los métodos y atributos sean estáticos, pero eliminar el singleton de está.
Por cuestiones de practicidad creo que sería mejor la opción de que sean estáticos y eliminar el singleton.

**Comment by Gann4Life** [comment]
De momento parece tener sentido el remover el patrón de singleton, ya que no usamos atributos dentro de la clase, más bien implementamos métodos que se pueden usar de manera universal y no es necesario establecer siquiera una instancia de la clase, hago la modificación y la envío para las pruebas, creo que no modificaría el comportamiento existente en absoluto. Hay que ver con los otros gestores como se ve esto del patrón de singleton.
