### ISSUE TITLE
Turnos pendiente

### ISSUE THREAD

**Issue by GiaBab** [Gann4Life/TP2FINAL#8]
mientras estaba pensando que test aplicar, me di cuenta que los turnos pendientes como esta ahora puede generar muchos errores, por lo que se me ocurrió que se aplique esto cada vez que se haga una modificación en la lista de turnos para actualizar a ratos turnos pendientes. 
baseDeDatos.turnos.getDatos().stream().filter(t -> t.estado == EstadoTurno.PENDIENTE).collect(Collectors.toCollection(ArrayList::new));
o sino aplicarlo en gestionDeTrunos como un method mas y borrar el atributo de la BDD

![image](https://user-images.githubusercontent.com/102558789/200199300-e13aefb8-24c2-411b-b3f4-4be1765be1f0.png)

**Comment by Gann4Life** [comment]
¿Qué clase de errores podría generar?
Veo mucho más acorde que eso se maneje a través del gestor de turnos, tiene más sentido así.  ¿Hay algo que sugieras hacer o cambiar?

**Comment by Gann4Life** [comment]
¿Qué clase de errores podría generar?
Veo mucho más acorde que eso se maneje a través del gestor de turnos, tiene más sentido así.  ¿Hay algo que sugieras hacer o cambiar?

EDIT: Recién acabo de entender el funcionamiento.
Supongo que una función que filtre los turnos pendientes sería útil.

**Comment by Gann4Life** [comment]
Debido a un error que tengo con el proyecto (el cual voy a revisar mañana a la mañana) necesito que te encargues de agregar una función en la clase de gestión de turnos que obtenga los turnos con un estado específico.
Dejo esto como base, el tipo de valor que devuelve puede cambiar en caso de ser necesario, pero mi idea es que devuelva una lista de turnos en base a un estado concreto para nosotros darle uso más tarde.

```java
public static List<Turno> turnosEnEstado(EstadoTurno estado) {
    // Code here
}
```

Un objetivo opcional sería hacer ésta función privada, y luego hacer funciones públicas que accedan a un estad concreto (para no hacer uso de los imports en los tests por ejemplo o algo por el estilo, no estoy seguro) por ejepmlo agregando `+turnosPendientes(): List<Turno>` (el cual haría uso de `-turnosConEstado(): List<Turno>`
Dejo un ejemplo también de esta opcion:
```java
private ArrayList<Turno> turnosConEstado(EstadoTurno estado) {
    // Code here
}

public static List<Turno> turnosPendientes() {
    turnosConEstado(EstadoTurno.PENDIENTE);
}

```

**Comment by GiaBab** [comment]
ahi estaría, lo tuve que hacer con ArrayList porque se me complico un poco con List
